# Generated by Django 6.0.7 on 2026-07-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_educationmodel_experiencemodel_projectmodel_and_more'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfoModel',
            new_name='UserModel',
        ),
    ]
