# Generated by Django 6.0.7 on 2026-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_rename_userinfomodel_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_image/'),
        ),
    ]
