# Generated by Django 6.0.7 on 2026-07-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_usermodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='profile_image/')),
                ('address', models.TextField(null=True)),
                ('social_link', models.URLField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='social_link',
        ),
    ]
